routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'auth'],function(){
    Route::get('/', function () {
        return view('home');
    })->name('home');
//    Route::any('user/create','UserController@create')->name('user.store');
//    Route::get('user','UserController@index')->name('user.index');
    Route::resource('user', 'UserController');
  
    Route::resource('urlgroups', 'UrlGroupController');
    Route::resource('urls', 'UrlController');
    Route::resource('usertypes', 'UserTypeController');
    Route::any('batchUpdate','UserTypeController@batchUpdate')->name('usertypes.batchUpdate');
    Route::post('language-switcher','LanguageController@switchLanguage');
    Route::post('/language/',array(
                                    'before' => 'csrf' ,
                                    'as' => 'language-switcher' ,
                                    'uses' => 'LanguageController@switchLanguage'
                                   )
    );
});


Route::get('/login', function () {
    return view('auth.login');
});

Route::group(['namespace'=>'Auth'],function(){
    Route::post('/login', ['uses'=>'LoginController@login'])->name('login.post');
    Route::get('/logout', ['uses'=>'LoginController@logout'])->name('auth.logout');
});

app/Http/Controllers/UserTypeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\UserType;
use Illuminate\Support\Facades\DB;

class UserTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $user_types;

    public function __Construct(){

        $this->user_types = UserType::all();
     }


    public function index()
    {
        $user_types = $this->user_types;
        return view('usertypes.index',compact('user_types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('usertypes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dbSuccsess = false;
        $error = 'Unknown error - Store';
        DB::beginTransaction();
        try {
            $userType_data = [];

            $userType_data['name'] = $request->name;

            UserType::create($userType_data);
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user_types = UserType::find($id);
        $query = "
                    SELECT G.name as url_group
                          ,U.id   as url_id
                          ,U.name as url_name
                          , Case When T.user_type_id is not null
                            then 'checked'
                            else ''
                            end  Checked  
                    FROM url_groups AS G
                      left JOIN urls AS U
                        on(G.id = U.url_group_id)
                      left JOIN user_type_url AS T
                        on(T.url_id = U.id) and T.user_type_id = ".$id
                    ." Order by G.name , U.id  asc";

        $links = collect(DB::Select("$query"));
        return view('usertypes.edit',compact('user_types','links'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


    }

    public function batchUpdate(Request $request)
    {
        $dbSuccsess = false;
        $error = 'Unknown error - batchUpdate';
        DB::beginTransaction();

        try {
            $usertype = UserType::find($request->user_type_id);
            $usertype->urls()->detach();
            foreach($request->url_id as $url)
            {
                $usertype->urls()->attach($url);
            }
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/usertypes/create.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Create New User Role</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>User Role</b> Was Not Done.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create User Role!</h4>
        <b>You Could Create New User Role</b> that fit your users need.
    </div>

    <div class="col-md-12">
        <div class="col-md-6">
            <div class="white-box">
                <h3 class="box-title m-b-0">Add and create Create User Role</h3>
                <p class="text-muted m-b-30 font-13"> Create roles for users </p>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form id='#form' method="post" action="{{route('usertypes.store')}}">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">Role Name</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                            <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('.page-title').html('Create Role');
        });
    </script>
@stop

resources/views/usertypes/edit.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Update User Role</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>User Role Update</b> Was Not Done.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Update User Role!</h4>
        <b>You Could Update New User Role</b> that fit your users need.
    </div>
    <div class="col-md-12">
            <div class="white-box">
                <h4 class="box-title m-b-0">Edit - <b style="color:orangered;">{{$user_types->name}}</b> - Role</h4>
                <p class="text-muted m-b-30 font-13"> Edit Role Children and assign or remove links </p>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form id='#form' method="patch" action="{{route('usertypes.batchUpdate')}}">
                            <input type="text" name="user_type_id" value="{{$user_types->id}}" hidden>
                            @php
                                $start = 0;
                                $oldlink;
                            @endphp
                            @foreach($links as $link)
                                    @if(empty($oldlink))
                                    <div class="form-group">
                                        <div class="alert alert-info"><h4>{{$link->url_group}}</h4></div>
                                    </div>
                                        @php
                                            $oldlink = $link->url_group;
                                        @endphp
                                    @elseif(!empty($oldlink) && $oldlink != $link->url_group)
                                            @php
                                                $oldlink = $link->url_group;
                                            @endphp
                                            <hr>
                                            <div class="form-group">
                                                <div class="alert alert-info"><h4>{{$link->url_group}}</h4></div>
                                            </div>
                                            <hr>
                                    @else
                                    @endif

                                        <div align="left" class="form-group">
                                            <input name="url_id[{{$start}}]" id="url_id" type="checkbox" value="{{$link->url_id}}" {{$link->Checked}}>
                                            <label for="name">{{$link->url_name}}</label>
                                        </div>
                                @php $start++; @endphp
                            @endforeach

                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                            <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('.page-title').html('Edit Role Details');
        });
    </script>
@stop

resources/views/usertypes/index.blade.php
@extends('layout')
@section('content')
    <a href="{{route('usertypes.create')}}" class="btn btn-info">
        Add New Role <i class="fa fa-plus fa-lg"></i>
    </a>
    <hr>
    <table Class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>SN</th>
            <th>Role Name</th>
            <th>Creation Date</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php $i=1; ?>
        @foreach($user_types as $user_type)
            <tr>
                <td>{{$i}}</td>
                <td>{{$user_type->name}}</td>
                <td>{{$user_type->created_at}}</td>
                <td>
                    <a class="btn btn-info" href="{{route('usertypes.edit',$user_type->id)}}">
                        <i Class="fa fa-pencil fa-lg"></i>
                    </a>
                    {{--<a class="btn btn-danger" href="{{route('usertypes.edit',$user_type->id)}}">--}}
                        {{--<i Class="fa fa-trash fa-lg"></i>--}}
                    {{--</a>--}}
                </td>
            </tr>
            <?php $i++; ?>
        @endforeach
        </tbody>
    </table>
@stop

@section('script')
    <script>
        $(document).ready(function(){
            $('.page-title').html('User Groups');

        });
    </script>
@stop