routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'auth'],function(){
    Route::get('/', function () {
        return view('home');
    })->name('home');
//    Route::any('user/create','UserController@create')->name('user.store');
//    Route::get('user','UserController@index')->name('user.index');
    Route::resource('user', 'UserController');
  
    Route::resource('urlgroups', 'UrlGroupController');
    Route::resource('urls', 'UrlController');
    Route::resource('usertypes', 'UserTypeController');
    Route::any('batchUpdate','UserTypeController@batchUpdate')->name('usertypes.batchUpdate');
    Route::post('language-switcher','LanguageController@switchLanguage');
    Route::post('/language/',array(
                                    'before' => 'csrf' ,
                                    'as' => 'language-switcher' ,
                                    'uses' => 'LanguageController@switchLanguage'
                                   )
    );
});


Route::get('/login', function () {
    return view('auth.login');
});

Route::group(['namespace'=>'Auth'],function(){
    Route::post('/login', ['uses'=>'LoginController@login'])->name('login.post');
    Route::get('/logout', ['uses'=>'LoginController@logout'])->name('auth.logout');
});

app/Url.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Url extends Model
{
    protected $table = 'urls';
    protected $fillable =['name','href','order','url_group_id'];

    public function url_group(){
        return $this->belongsTo(UrlGroup::class,'url_group_id','id');
    }

    public function user_types(){
        return $this->belongsToMany(UserType::class,'user_type_url','url_id','user_type_id');
    }
}

app/Http/Controllers/UrlController.php
<?php

namespace App\Http\Controllers;

use App\UrlGroup;
use App\UserType;
use App\Url;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Mockery\Exception;

class UrlController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $query = "Select 
                         u.id
                       , u.href 
                       , u.order 
                       , u.name as description 
                       , u.created_at
                       , t.name as urlgroup
                  from urls u left join url_groups t 
                  on (u.url_group_id=t.id);";

        $urls = DB::Select($query);
        return view('urls.index',compact('urls','user_types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $url_groups = UrlGroup::all();
        return view('urls.create',compact('url_groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dbSuccsess = false;
        $error = 'Unknown error - Store';
        $url_data = [];
        DB::beginTransaction();
        try{
            $url_data['href'] = $request->href;
            $url_data['name'] = $request->name;
            $url_data['order'] = $request->order;
            $url_data['url_group_id'] = $request->url_group_id;

            Url::create($url_data);
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $url = Url::find($id);
        $url_groups = UrlGroup::all();
        return view('urls.edit',compact('url','url_groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $url = Url::find($id);

        $this->validate($request,[
            'name'=> 'required',
            'href'=>'bail|required',
            'url_group_id'=>'bail|required',
        ]);

        $dbSuccsess = false;
        $error = 'Unknown error - Store';
        DB::beginTransaction();
        try {
            $url->update($request->input());
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dbSuccsess=false;
        $error = 'Unknown error - destroy';

        DB::beginTransaction();
        try
        {
            Url::find($id)->delete();
            $dbSuccsess=true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }
}

resources/views/urls/create.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Create New URL</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>URL</b> Was Not Sent.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create URL!</h4>
        <b>You Could Create URL</b> for the NAV bar.
    </div>
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="white-box">
                <h3 class="box-title m-b-0">Second Step : Create Urls</h3>
                <p class="text-muted m-b-30 font-13"> Create a child Url and assign it to Parent Group Url group </p>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form id='#form' method="post" action="{{route('urls.store')}}">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">href</label>
                                <input type="text" name="href" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <div class="form-group">
                                <label for="name">Url title</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <div class="form-group">
                                <label for="name">Group Name</label>
                                <select name="url_group_id" class="form-control" id="url_group_id" required>
                                    <option value=""></option>
                                    @foreach($url_groups as $url_group)
                                        <option value="{{$url_group->id}}">{{$url_group->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="name">Order</label>
                                <input type="number" name="order" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                            <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('.page-title').html('Create Url');
        });
    </script>
@stop

resources/views/urls/edit.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Edit URL</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>URL</b> Was Not Updated.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Edit URL!</h4>
        <b>You Could Edit URL</b> for the NAV bar.
    </div>
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="white-box">
                <h3 class="box-title m-b-0">Edit Urls</h3>
                <p class="text-muted m-b-30 font-13"> Edit a child Url and assign it to New Parent Group Url group </p>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        {!!Form::open(['method' => 'patch','route' => ['urls.update', $url->id]])!!}
                        {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">href</label>
                                <input type="text" name="href" class="form-control" value="{{$url->href}}" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <div class="form-group">
                                <label for="name">Url title</label>
                                <input type="text" name="name" class="form-control" value="{{$url->name}}" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <div class="form-group">
                                <label for="name">Group Name</label>
                                <select name="url_group_id" class="form-control" id="url_group_id" required>
                                    <option value=""></option>
                                    @foreach($url_groups as $url_group)
                                        <option value="{{$url_group->id}}"
                                        @if($url_group->id == $url->url_group_id)
                                                selected="selected"
                                        @endif
                                                >{{$url_group->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="name">Order</label>
                                <input type="number" name="order" value="{{$url->order}}" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                            <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('.page-title').html('Create Url');
        });
    </script>
@stop

resources/views/urls/index.blade.php
@extends('layout')
@section('content')

    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Delete User</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>User</b> Was Not Deleted.
    </div>

    @if(session()->has('error') || count($errors->all()) > 0)
        <div class="myadmin-alert myadmin-alert-img myadmin-alert-click alert-danger myadmin-alert-bottom alertbottom2" style="display: block;"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">×</a>
            <h4>Please Report the Following Errors</h4>
            <b></b> {{session()->get('error')}} <a href="#" class="closed">×</a> <br>
            @if(count($errors->all() > 0))
                @foreach($errors->all() as $error_val)
                    <b></b> {{$error_val}} <a href="#" class="closed">×</a> <br>
                @endforeach
            @endif
        </div>
    @endif

    <a href="{{route('urls.create')}}" class="btn btn-info">
       Add New URL <i class="fa fa-plus fa-lg"></i>
    </a>
    <hr>
    <table Class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>SN</th>
            <th>Description</th>
            <th>href</th>
            <th>Order</th>
            <th>Group</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php $i=1; ?>
        @foreach($urls as $url)
            <tr>
                <td>{{$i}}</td>
                <td>{{$url->description}}</td>
                <td>{{$url->href}}</td>
                <td>{{$url->order}}</td>
                <td>{{$url->urlgroup}}</td>
                <td>
                    {!!Form::open(['method' => 'delete','route' => ['urls.destroy', $url->id]])!!}
                    {{ csrf_field() }}
                    <a href="{{route('urls.edit',$url->id)}}" Class="btn btn-info"><i Class="fa fa-lg fa-pencil"></i></a>
                    <button type="submit" Class="btn btn-danger"><i Class="fa fa-lg fa-trash"></i></button>
                    {!!Form::close()!!}
                </td>
            </tr>
            <?php $i++; ?>
        @endforeach
        </tbody>
    </table>
@stop

@section('script')
    <script>
        $(document).ready(function(){
            $('.page-title').html('URL Management');

        });
    </script>
@stop