routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'auth'],function(){
    Route::get('/', function () {
        return view('home');
    })->name('home');
//    Route::any('user/create','UserController@create')->name('user.store');
//    Route::get('user','UserController@index')->name('user.index');
    Route::resource('user', 'UserController');
  
    Route::resource('urlgroups', 'UrlGroupController');
    Route::resource('urls', 'UrlController');
    Route::resource('usertypes', 'UserTypeController');
    Route::any('batchUpdate','UserTypeController@batchUpdate')->name('usertypes.batchUpdate');
    Route::post('language-switcher','LanguageController@switchLanguage');
    Route::post('/language/',array(
                                    'before' => 'csrf' ,
                                    'as' => 'language-switcher' ,
                                    'uses' => 'LanguageController@switchLanguage'
                                   )
    );
});


Route::get('/login', function () {
    return view('auth.login');
});

Route::group(['namespace'=>'Auth'],function(){
    Route::post('/login', ['uses'=>'LoginController@login'])->name('login.post');
    Route::get('/logout', ['uses'=>'LoginController@logout'])->name('auth.logout');
});

app/UrlGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UrlGroup extends Model
{
    protected $table = 'url_groups';
    protected $fillable = ['name','href','order'];

    public function urls(){
        return $this->hasMany(Url::class,'url_group_id','id');
    }
}

app/Http/Controllers/UrlGroupController.php
<?php

namespace App\Http\Controllers;

use App\UrlGroup;
use Illuminate\Http\Request;
use Mockery\Exception;

class UrlGroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $url_groups = UrlGroup::all();
        return view ('urlgroups.index',compact('url_groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('urlgroups.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dbSuccsess = false;
        $error = 'Unknown error - Store';
        $url_data = [];
        DB::beginTransaction();
        try {
            $url_data = [];

            $url_data['href'] = $request->href;
            $url_data['name'] = $request->name;
            $url_data['order'] = $request->order;

            UrlGroup::Create($url_data);
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/urlgroups/create.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Create New URL Group</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>URL</b> Was Not Sent.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create URL Group!</h4>
        <b>You Could Create URL Group</b> for the NAV bar.
    </div>
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="white-box">
                <h3 class="box-title m-b-0">First Step : Create Url Group</h3>
                <p class="text-muted m-b-30 font-13">Create Url Groups for Navigation bar which will be the parent for Urls too</p>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        <form id='#form' method="post" action="{{route('urlgroups.store')}}">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">href</label>
                                <input type="text" name="href" class="form-control" id="name" value="#" placeholder="Enter Group Name" required>
                            </div>
                            <div class="form-group">
                                <label for="name">Url description</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <div class="form-group">
                                <label for="name">Order</label>
                                <input type="number" name="order" class="form-control" id="name" placeholder="Enter Group Name" required>
                            </div>
                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                            <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <script>
        $(document).ready(function() {
            $('.page-title').html('Create Url Groups');
        });
    </script>
@stop

resources/views/urlgroups/index.blade.php
@extends('layout')
@section('content')
    <a href="{{route('urlgroups.create')}}" class="btn btn-info">
        Add New URL Group <i class="fa fa-plus fa-lg"></i>
    </a>
    <hr>
    <table Class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>SN</th>
            <th>Link</th>
            <th>Group Name</th>
            <th>Order</th>
            <th>Creation Date</th>
        </tr>
        </thead>
        <tbody>
        <?php $i=1; ?>
        @foreach($url_groups->sortBy('order') as $url)
            <tr>
                <td>{{$i}}</td>
                <td>{{$url->href}}</td>
                <td>{{$url->name}}</td>
                <td>{{$url->order}}</td>
                <td>{{$url->created_at}}</td>
            </tr>
            <?php $i++; ?>
        @endforeach
        </tbody>
    </table>
@stop

@section('script')
    <script>
        $(document).ready(function(){
            $('.page-title').html('URL Group');

        });
    </script>
@stop