routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>'auth'],function(){
    Route::get('/', function () {
        return view('home');
    })->name('home');
//    Route::any('user/create','UserController@create')->name('user.store');
//    Route::get('user','UserController@index')->name('user.index');
    Route::resource('user', 'UserController');
  
    Route::resource('urlgroups', 'UrlGroupController');
    Route::resource('urls', 'UrlController');
    Route::resource('usertypes', 'UserTypeController');
    Route::any('batchUpdate','UserTypeController@batchUpdate')->name('usertypes.batchUpdate');
    Route::post('language-switcher','LanguageController@switchLanguage');
    Route::post('/language/',array(
                                    'before' => 'csrf' ,
                                    'as' => 'language-switcher' ,
                                    'uses' => 'LanguageController@switchLanguage'
                                   )
    );
});


Route::get('/login', function () {
    return view('auth.login');
});

Route::group(['namespace'=>'Auth'],function(){
    Route::post('/login', ['uses'=>'LoginController@login'])->name('login.post');
    Route::get('/logout', ['uses'=>'LoginController@logout'])->name('auth.logout');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $table = 'users';
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','username' ,'email', 'password','user_type_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function user_type(){
        return $this->belongsTo(UserType::class,'user_type_id','id');
    }
    public function Patient(){
        return $this->hasMany(Patient::class,'user_id','id');
        }
        public function RequestHeader(){
        return $this->hasMany(RequestHeader::class,'user_id','id');
        }
}

app/UserType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    protected $table = 'user_types';
    protected $fillable= ['name'];

    public function users(){
        return $this->hasMany(User::class,'user_type_id','id');
    }

    public function urls(){
        return $this->belongsToMany(Url::class,'user_type_url','user_type_id','url_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\UserType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function __construct()
    {
    }

    public function create(){

        $userTypes = UserType::all();
        return view('user.create' , compact('userTypes'));
    }

    public function index()
    {
        $users = DB::Select("Select u.id , u.name , u.email , u.created_at  , t.name as group_name ,u.username
                             from users u left join user_types t on (u.user_type_id=t.id)");
        return view('user.index',compact('users'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=> 'required',
            'email'=>'bail|required|unique:users',
            'username'=>'bail|required|min:4|unique:users',
            'password'=>'bail|required|min:6',
            'password_confirmation'=>'bail|required|min:6|same:password',
            'user_type_id'=>'bail|required'
        ]);
        $dbSuccsess = false;
        $error = 'Unknown error - Store';
        DB::beginTransaction();
        try {
            $user_data = [];

            $user_data['name'] = $request->name;
            $user_data['email'] = $request->email;
            $user_data['password'] = bcrypt($request->password);
            $user_data['user_type_id'] = $request->user_type_id;
            $user_data['username'] = $request->username;

            User::create($user_data);
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->route('user.index')
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->route('user.index')
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    public function edit ($id)
    {
        $user = User::find($id);
        $userTypes = UserType::all();
        return view('user.edit',compact('user','userTypes'));
    }

    public function update (Request $request, $id)
    {
        $user = User::find($id);

        $this->validate($request,[
            'name'=> 'required',
            'email'=>'bail|required|unique:users,email,'.$user->id,
            'username'=>'bail|required|unique:users,username,'.$user->id,
//            'password'=>'bail|required|min:6',
//            'password_confirmation'=>'bail|required|min:6|same:password',
            'user_type_id'=>'bail|required'
        ]);

        $dbSuccsess = false;
        $error = 'Unknown error - Store';
        DB::beginTransaction();
        try {
            $user->update($request->input());
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    public function destroy ($id)
    {
        $dbSuccsess=false;
        $error = 'Unknown error - Store';

        $user = User::find($id);

        DB::beginTransaction();
        try {
        $user->find($id)->delete();
        $dbSuccsess=true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }


    public function show($id)
    {
        return redirect()->back();
    }






}

resources/views/user/create.blade.php
@extends('home')
@section('content')
    {{--
            'name'=>'required',
            'username'=>'bail|required|min:6|unique:users',
            'password'=>'bail|required|min:6',
            'password_confirmation'=>'confirmed',
            'user_type'=>'required'
    --}}
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Create New User</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>User</b> Was Not Sent.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create User!</h4>
        <b>You Could Create New User</b> Choose User Role Carefully.
    </div>

    @if(session()->has('error') || count($errors->all()) > 0)
        <div class="myadmin-alert myadmin-alert-img myadmin-alert-click alert-danger myadmin-alert-bottom alertbottom2" style="display: block;"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">×</a>
            <h4>Please Report the Following Errors</h4>
            <b></b> {{session()->get('error')}} <a href="#" class="closed">×</a> <br>
            @if(count($errors->all() > 0))
                @foreach($errors->all() as $error_val)
                    <b></b> {{$error_val}} <a href="#" class="closed">×</a> <br>
                @endforeach
            @endif
        </div>
    @endif


<div class="col-md-12">
    <div class="col-md-6">
        <div class="white-box">
            <h3 class="box-title m-b-0">Create User</h3>
            <p class="text-muted m-b-30 font-13"> Create User and add it to a group </p>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <form id='#form' method="post" action="{{route('user.store')}}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Full Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter Full Name" required>
                        </div>
                        <div class="form-group">
                            <label for="username">User Name</label>
                            <input type="text" name="username" class="form-control" id="username" placeholder="Enter Username" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" required>
                        </div>
                        <div class="form-group">
                            <label for="password1">Password</label>
                            <input type="password" name="password" class="form-control" id="password1" placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <label for="password2">Password</label>
                            <input type="password" name="password_confirmation" class="form-control" id="password" placeholder="Confirm Password" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Group</label>
                            <Select class="form-control" name="user_type_id" id="user_type_id" placeholder="Choose Group" required>
                                <option value=""></option>
                                @foreach($userTypes as $userType)
                                    <option value="{{$userType->id}}">{{$userType->name}}</option>
                                @endforeach
                            </Select>
                        </div>
                        {{--<div class="form-group">--}}
                            {{--<label class="col-sm-12">Profile Image</label>--}}
                            {{--<input type="file" name="profileimage" class="form-control" id="profileimage" placeholder="profileimage">--}}
                        {{--</div>--}}
                        <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                        <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="white-box">

        </div>
    </div>
</div>
@stop

@section('script')
    <script src="{{asset('plugins/bower_components/jquery-validation/dist/jquery.validate.js')}}"></script>
    <script src="{{asset('plugins/bower_components/jquery-validation/dist/jquery.validate.min.js')}}"></script>

    <script>
        $(document).ready(function(){

            $('.page-title').html('Create User');

            $('#form').validate({
                rules: {
                    password: {
                        required: true,
                        minlength: 6,
                        maxlength: 30,
                    } ,
                    password_confirmation: {
                        equalTo: "#password",
                        minlength: 6,
                        maxlength: 30
                    }
                },
                messages:{
                    password: {
                        required:"the password is required"
                    }
                }
            });
        });
    </script>
@stop

resources/views/user/edit.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Edit User</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>User</b> Was Not Updated.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Edit User!</h4>
        <b>You Could Edit User</b> While Choosing User Role Carefully.
    </div>

    @if(session()->has('error') || count($errors->all()) > 0)
        <div class="myadmin-alert myadmin-alert-img myadmin-alert-click alert-danger myadmin-alert-bottom alertbottom2" style="display: block;"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">×</a>
            <h4>Please Report the Following Errors</h4>
            <b></b> {{session()->get('error')}} <a href="#" class="closed">×</a> <br>
            @if(count($errors->all() > 0))
                @foreach($errors->all() as $error_val)
                    <b></b> {{$error_val}} <a href="#" class="closed">×</a> <br>
                @endforeach
            @endif
        </div>
    @endif

    <div class="col-md-12">
        <div class="col-md-6">
            <div class="white-box">
                <h3 class="box-title m-b-0">Create User</h3>
                <p class="text-muted m-b-30 font-13"> Create User and add it to a group </p>
                <div class="row">
                    <div class="col-sm-12 col-xs-12">
                        {{--<form id='#form' method="put" action="{{route('user.update',$user->id)}}">--}}
                            {!!Form::open(['method' => 'patch','route' => ['user.update', $user->id]])!!}
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">Full Name</label>
                                <input type="text" name="name" class="form-control" value="{{$user->name}}" id="name" placeholder="Enter Full Name" required>
                            </div>
                            <div class="form-group">
                                <label for="username">User Name</label>
                                <input type="text" name="username" class="form-control" value="{{$user->username}}" id="username" placeholder="Enter Username" required>
                            </div>
                            <div class="form-group">
                                <label for="email">Email address</label>
                                <input type="email" name="email" class="form-control" value="{{$user->email}}" id="email" placeholder="Enter email" >
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Group</label>
                                <Select class="form-control" name="user_type_id" id="user_type_id" placeholder="Choose Group" required>
                                    <option value=""></option>
                                    @foreach($userTypes as $userType)
                                        <option value="{{$userType->id}}"
                                                @if($userType->id == $user->user_type_id)
                                                selected="selected"
                                                @endif
                                        >{{$userType->name}}</option>
                                    @endforeach
                                </Select>
                            </div>
                            {{--<div class="form-group">--}}
                            {{--<label class="col-sm-12">Profile Image</label>--}}
                            {{--<input type="file" name="profileimage" class="form-control" id="profileimage" placeholder="profileimage">--}}
                            {{--</div>--}}
                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                            <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="white-box">

            </div>
        </div>
    </div>

@stop
@section('script')
    <script>
        $(document).ready(function(){
            $('.page-title').html('Edit User');
        });
    </script>
@stop

resources/views/user/index.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Delete User</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>User</b> Was Not Deleted.
    </div>

    <a href="{{route('user.create')}}" class="btn btn-info">
        Add New User <i class="fa fa-plus fa-lg"></i>
    </a>
    <hr>
    <table Class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>SN</th>
                <th>Full Name</th>
                <th>User Name</th>
                <th>Group</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @php
            $i=1;
        @endphp
            @foreach($users as $user)
                <tr>
                    <td>{{$i}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->username}}</td>
                    <td>{{$user->group_name}}</td>
                    <th>
                        {!!Form::open(['method' => 'delete','route' => ['user.destroy', $user->id]])!!}
                        {{ csrf_field() }}
                        <a href="{{route('user.edit',$user->id)}}" Class="btn btn-info"><i Class="fa fa-lg fa-pencil"></i></a>
                        <button type="submit" Class="btn btn-danger"><i Class="fa fa-lg fa-trash"></i></button>
                        {!!Form::close()!!}
                    </th>
                </tr>
            @php
                $i++;
            @endphp
            @endforeach
        </tbody>
    </table>
@stop

@section('script')
    <script>
        $(document).ready(function(){
            $('.page-title').html('Create User');

        });
    </script>
@stop